# Generated by Django 2.1.2 on 2018-10-30 23:05

import contas.models.usuario
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
    ]
