# Generated by Django 2.1.2 on 2018-10-31 20:27

import contas.models.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'proxy': True,
                'indexes': [],
            },
            bases=('contas.usuario',),
            managers=[
                ('objects', contas.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
