# Generated by Django 2.1.2 on 2018-10-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=5, unique=True, verbose_name='Sigla')),
                ('sobre', models.TextField(null=True, verbose_name='Sobre o curso')),
                ('duracao', models.SmallIntegerField(verbose_name='Semestres')),
                ('tipo', models.CharField(choices=[('T', 'Tecnólogo')], max_length=1, verbose_name='Tipo')),
                ('noturno', models.BooleanField(verbose_name='Noturno?')),
                ('diurno', models.BooleanField(verbose_name='Diurno?')),
            ],
            options={
                'db_table': 'CURSO',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('identificador', models.CharField(max_length=30, unique=True, verbose_name='Identificador')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberta'), ('FECHADO', 'Fechada')], max_length=10, verbose_name='Status')),
                ('carga_horaria', models.SmallIntegerField(verbose_name='Carga Horária')),
                ('percentual_pratico', models.SmallIntegerField(verbose_name='Percentual Prático')),
                ('percentual_teorico', models.SmallIntegerField(verbose_name='Percentual Teórico')),
                ('plano_de_ensino', models.TextField(blank=True, verbose_name='Plano de Ensino')),
                ('competencias', models.TextField(blank=True, verbose_name='Competências')),
                ('habilidades', models.TextField(blank=True, verbose_name='Habilidades')),
                ('ementa', models.TextField(blank=True, verbose_name='Ementa')),
                ('conteudo_programatico', models.TextField(blank=True, verbose_name='Conteúdo Programático')),
                ('bibliografia_basica', models.TextField(blank=True, verbose_name='Bibliografia Básica')),
                ('bibliografia_complementar', models.TextField(blank=True, verbose_name='Bibliografia Complementar')),
            ],
            options={
                'db_table': 'DISCIPLINA',
            },
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('semestre', models.SmallIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')], verbose_name='Semestre')),
                ('turma', models.CharField(max_length=1, verbose_name='Turma')),
                ('data_inicio', models.DateField(verbose_name='Data Ínicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('metodologia', models.TextField(blank=True, verbose_name='Metodologia')),
                ('recursos', models.TextField(blank=True, verbose_name='Recursos')),
                ('criterio_de_avaliacao', models.TextField(blank=True, verbose_name='Critério de Avaliação')),
                ('plano_de_aulas', models.TextField(blank=True, verbose_name='Plano de Aulas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplina')),
            ],
            options={
                'db_table': 'DISCIPLINA_OFERTADA',
            },
        ),
    ]
