# Generated by Django 2.1.2 on 2018-10-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('T', 'Tecnólogo'), ('G', 'Graduação')], max_length=1, verbose_name='Tipo'),
        ),
    ]
